### ISSUE TITLE
Serious security vulnerabiliy: XSS (Cross Site Scripting)

### ISSUE THREAD

**Issue by xmcp** [ht35268/bzShare#1]
If the uploaded filename contains malicious content, such as:

- `foo<script>alert(/xss/</script>.txt`
- `foo"autofocus="autofocus"onfocus="alert(/xss/)"unused=".txt`

The malicious script will be injected into the HTML webpage.

## Solution:

Escape the input.

## See Also:

https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

**Comment by ht35268** [comment]
I would not only choose to escape the input but also limit a variety of characters that would be allowed to use. Serious things like <> would be banned.

Security measures would be taken within the forgery of SQLFS.

#2
