### ISSUE TITLE
Literally this is not an issue

### ISSUE THREAD

**Issue by xmcp** [ht35268/bzShare#13]
![image](https://cloud.githubusercontent.com/assets/6646473/18131856/f85d3a6a-6fc6-11e6-8381-a1d0a7597266.png)

well... namespace in JS is a good thing, but obviously this is not the correct usage of that.

**Comment by ht35268** [comment]
I admit.

I had always been confusing about these lines of code and is seriously obfuscated by it... I do hate writing like this. But as this is a quick and (un)tidy project...

I give up.

Going to fix this later. Keep reminding me pls.

**Comment by xmcp** [comment]
well, i mean the `javascript:`.

**Comment by ht35268** [comment]
I decided that this style of writing may be useful and decided not to change this.
