### ISSUE TITLE
Importing is recursive in SQLFS, making it impposible to load

### ISSUE THREAD

**Issue by xmcp** [ht35268/bzShare#20]
![image](https://cloud.githubusercontent.com/assets/6646473/18231212/24f92c0c-72e5-11e6-87c3-084214124069.png)

In a word, `sqlfs/__init__.py` requires `sqlfs/file_system_permissions.py`, which requires `users.py`, which requires `sqlfs/__init__.py` itself.

So I'm wondering how can you make this code runnable in your PC.

**Comment by ht35268** [comment]
I'm quite wondering how did you get those issues!

I work on Windows, really. But **theoretically** Python on Linux should work the same as Python on MinGW if not recurring `os`.

Either way, I don't have recursive importing errors, anyway.

**Comment by ht35268** [comment]
Does the User() hurt anyway?

I'm looking forward to that.

**Comment by xmcp** [comment]
i don't know whether the `User()` issue is fixed because the code crashes BEFORE those code are reached…… all right, i gave up switching to a win8 VM.

**Comment by ht35268** [comment]
Hey! Linux is where we would be deploying to!

**Comment by xmcp** [comment]
so you should try this code on linux. litteraly this code SHOULDN'T BE WORKING as its dependency relationship is broken,

**Comment by ht35268** [comment]
I was aware of that but I tried not to panic. I tried the same type of code (cross importing) on other snippets and it worked just fine on Windows.

Now I am wondering who (the *****) ported Python to Windows in such a brainless way.

**Comment by ht35268** [comment]
[http://blog.csdn.net/jq0123/article/details/1527148](http://blog.csdn.net/jq0123/article/details/1527148)

There is an article attributing to this problem.
Maybe it's just because of cross referencing and we did them in the wrong way.

I'm installing VirtualBox by the time...

**Comment by ht35268** [comment]
So the problem is not cross / recursive importing... It is when we are importing we don't know what have we imported.

**Comment by xmcp** [comment]
**it is**. try to figure out what *exactly* you want to use in these 3 modules and put them in `utils`.

**Comment by ht35268** [comment]
I don't...

**Comment by ht35268** [comment]
Well, after a gruelsome configuration of Linux (Literally Ubuntu 14.04 with GNOME/GUI) and:

Python 3.5.2!
Python 3.5.2!
Python 3.5.2!

Important things should be attributed thrice.

There did not seem to be anything wrong with the code and the so seemed erroneous recursive importing did not happen to be going wrong. Please use Python 3.5.2.

In the case you didn't believe that this would work, I have a screenshot.

![screenshot from 2016-09-06 21-25-11](https://cloud.githubusercontent.com/assets/18145331/18275301/da62820c-7478-11e6-8504-43a01d2c713c.png)
