### ISSUE TITLE
Potential XSS: Multiple Content-Type headers in file download handler

### ISSUE THREAD

**Issue by xmcp** [ht35268/bzShare#21]
![image](https://cloud.githubusercontent.com/assets/6646473/18231704/92b13142-72f2-11e6-96e6-c91e0631acfe.png)

when downloading files, bzShare adds a `Content-Type: application/x-download` header, but doesn't remove the original one (`text/html`) that causes XSS vulnerability.

The result of this vulnerability varies from browsers:
- Chrome will choose the last one if multiple `Content-Type`s are shown. So browsers like Chrome are not affected by the vulnerability
- But some browsers like Internet Explorer will choose the first header, which are vulnerable.

See the screenshot below:
![image](https://cloud.githubusercontent.com/assets/6646473/18231709/a363cc66-72f2-11e6-9ee2-daec4890c4dd.png)

So you need to remove the original header(s) in the download handler.

**Comment by ht35268** [comment]
I noticed this vulnerability very earlier before your issue submit. But I regarded it simply as a verbosity, not a vulnerability. Now it seems to be an issue. I will fix this later.
