### ISSUE TITLE
Stop hashing passwords in the browser-side

### ISSUE THREAD

**Issue by xmcp** [ht35268/bzShare#25]
It's not recommended to hash the password **in the browser-side**.

The consideration of js performance is one of the reason, but the more important one is that hackers can still bypass the login by POSTing the hash, if they hacked into the db somehow.
So it's important to move the hashing algorithm to the backend, or at least **re-hash the javascript-generated hash** in the backend.

p.s. Remember that websites without HTTPS are still vulnerable, even used js-based cryptos. At this point, js-based cryptos **ARE NOT ABLE TO make the website safe**.

p.p.s. As SHA-512 runs very quickly, it's a best practice to iterate the hashing algorithm for thousands times. For Example:
```python
hashed = get_input_password()
salt = 'hfuivnuifhviurjiog'
for _ in range(5000):
    hashed = hash_function(salt + hashed)
```

**Comment by ht35268** [comment]
You mean... Hash in the browser and hash in the database?

**Comment by ht35268** [comment]
Yes... Originally I considered this approach, and immediately decided that it would be useless which was wrong indeed.

Now I am trying to add it. Shouldn't take a lot of time.

Just I had to re-hash all users' passwords in the database and re-upload them, which is really a nuisance. Lucky not many people registered themselves on bzShare.

**Comment by xmcp** [comment]
before:
```python
if request.form['hashed_psw'] == psw_in_db:
    return ACCESS_GRANTED
```

after:
```python
if hash_function(request.form['hashed_psw']) == psw_in_db:
    return ACCESS_GRANTED

# you can still keep the js-based hash stuff, but it is useless on improving the security
```

**Comment by ht35268** [comment]
I just wanted to make people's password invisible to me.

**Comment by ht35268** [comment]
How about this hash function:

```Python
def hash_password(inp):
    """ Create a high computational complexity password hashing algorithm. """
    magic_str = 'esloplwnmhcelfqbevnmjcxyhvshiejhdvecrebngyrsahqlirwtgpieopqwokdb'
    magic_num = 2333 # Laugh out loud
    magic_cnt = 42
    for i in range(0, magic_num):
        inp = utils.sha512_hex((magic_str + inp) * magic_cnt)
    return inp
```

**Comment by xmcp** [comment]
It's acceptable, but magic_cnt is a kind of useless (and time-consuming), as `sha512` itself is good enough for you.

p.s. See [shile/hasher.py](https://github.com/xmcp/shile/blob/master/hasher.py) for my super-secure hash algorithm.
Its highlight is that people (including site admins) can't even know whether a user exists :)
But its weak point is its `O(n)` complexity on verifying hashes.

**Comment by ht35268** [comment]
Well, I was on the point of thinking maybe people could use this time-consuming operation as a weak entry for DDoS attacks.

Even though I was sure nobody would even bother DDoSing this server.

**Comment by xmcp** [comment]
but time-consuming is **required** for anti-bruteforce consideration.
if you **really** care about DDoS, you should add some restrictions (e.g. IP limit) in the login handler.

**Comment by ht35268** [comment]
Shile was okay because nobody needs to know other people exists. bzShare is there because you need to know there's someone else exists on the platform. So encoding people's usernames don't make sense. B.T.W. the ownerships of the filesystem could betray them of their entities.

**Comment by ht35268** [comment]
I don't care about DDoS, and I approve of your opinion on:

 > time-consuming is required for anti-bruteforce consideration.

IP limit should be implemented, indefinitely, if not never. I am now researching on how you do your encoding...

**Comment by ht35268** [comment]
Do I need to add `magic_cnt` on top of MD100? Or it was unnecessary? I need an answer.

**Comment by xmcp** [comment]
Yes. Shile is totally anonymity-concerned, that:
- It's theorically impossible to prevent 2 users having the same username
- It's theorically impossible to prevent 2 users having the same username and password
- It's theorically impossible to count the number of all registered users

**Comment by xmcp** [comment]
`magic_count` is only used in the iteration.
so just pick a reasonable iterating count.

**Comment by ht35268** [comment]
So, on such a platform, you think 2333 would be sufficient?

**Comment by xmcp** [comment]
time yourself. a good hashing process should take about 0.05s~0.5s for efficiency and anti-bruteforcing.

**Comment by ht35268** [comment]
Okay. I will do the testing on time with `time.time()`.

**Comment by ht35268** [comment]
This shall do the job.
Time complexity around 0.11200594902038574 s -> 0.12502574920654297 s

```Python
def password_hashed(pswin):
    """ Create a high computational complexity password hashing algorithm. """
    def MD100_xmcp_shile(pswin):
        """ MD100 hashing algorithm created by @xmcp. Each call on this function
        causes 1 iteration and only. Source:

        https://github.com/xmcp/shile/blob/master/hasher.py """
        psw1=hashlib.sha224()
        psw1.update(pswin.encode())
        psw2=hashlib.sha256()
        psw2.update(pswin[::-1].encode())
        psw3=hashlib.sha384()
        psw3.update(pswin.center(100, 'a').encode())
        psw4=hashlib.sha512()
        psw4.update(pswin.swapcase().encode())
        psw5=hashlib.sha1()
        psw5.update(base64.b64encode(pswin.encode()))
        psw6=hashlib.md5()
        psw6.update(base64.b32encode(pswin.rjust(100, 'a').encode()))
        return psw1.hexdigest()[0:16] + psw2.hexdigest()[0:16] + \
               psw3.hexdigest()[0:16] + psw4.hexdigest()[0:16] + \
               psw5.hexdigest()[0:16] + psw6.hexdigest()[0:16]
    # Iterations...
    magic_str = 'esloplwnmhcelfqbevnmjcxyhvshiejhdvecrebngyrsahqlirwtgpieopqwokdb'
    magic_num = 233 # Laugh out loud
    magic_cnt = 42
    for i in range(0, magic_num):
        pswin = sha512_hex((magic_str + MD100_xmcp_shile(pswin)) * magic_cnt)
    return pswin
```

**Comment by ht35268** [comment]
I still don't think your `shile` ensures total anonymity. My disagreement falls on the point of not preventing people with the same usernames and the passwords. You may let someone know he's using some account, but in fact they are the same account - you just don't tell them.

**Comment by xmcp** [comment]
you can use user-id instead of username to distinct users at the backend. at this point, usernames are only something like nicknames.

**Comment by ht35268** [comment]
Why use user-ids? IDs are rather harder to enter than handles, which you can define them yourself. And once you expose some of your data into the database it poses a vulnerability.

**Comment by xmcp** [comment]
user input his handle and password -> the backend query database to log him in and fetch the user's ID -> backend store the ID in the user's session and implement permission system based on this ID -> user know nothing about his ID, everything happens automatically to him.

and what's the vulnerability?

**Comment by ht35268** [comment]
But it's harder to implement, that's all.

And I am a lazy person. :)

**Comment by ht35268** [comment]
But if you could do this thing with handles, why bother ID?

**Comment by xmcp** [comment]
it's all about anonymity: the user handle is only store in the session - not the database nor the filesystem.

**Comment by ht35268** [comment]
Ah... So I get it. You hash the user's handle and the permission system is based on his hashed handle, literally his User-ID. Is that how it works?

**Comment by ht35268** [comment]
I think our discussion needs to be moved to another issue...

I've updated the security measures and up to now, I think the problem that was attributed in this issue was solved (not including other issues). I'll post a commit over. Feel free to re-open this.

**Comment by xmcp** [comment]
yep. and my hash system (the `mask_code` in `hasher.py`) ensured a same handle can produce different hashes, making the handles totally uncrackable,

**Comment by ht35268** [comment]
Please move to [https://github.com/ht35268/bzShare/issues/26](https://github.com/ht35268/bzShare/issues/26).

**Comment by ht35268** [comment]
Please move to Issue #26.
